### ISSUE TITLE
v9.0.0 and Gphoto2 issue

### ISSUE THREAD

**Issue by Briffou** [photobooth-app/photobooth-app#773]
**Describe the bug**
Since I updated to v9 (no issue on v8), I have trouble configuring my DSLR (Nikon D5300). I'm able to take a picture but as soon as I take a picture I get in the logs:

```
ERROR
	26.août.26 11:54:21	service Gphoto2Backend interrupted at /home/thomas/.local/share/pipx/venvs/photobooth-app/lib/python3.13/site-packages/photobooth/services/backends/gphoto2.py:330, error: Error communicating with the camera: [-1] Erreur indéfinie	photobooth.utils.resilientservice	report	39
CRITICAL
	26.août.26 11:54:21	aborting capturing frame, camera disconnected? retry to connect [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	323
WARNING
	26.août.26 11:54:20	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:20	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:19	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:19	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:18	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:18	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:17	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:17	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:16	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:16	error capturing frame from DSLR: [-1] Erreur indéfinie	photobooth.services.backends.gphoto2	run_service	317
WARNING
	26.août.26 11:54:13	normal service operation failed (attempt 1). Retrying in 2s...
```

It seems that the connection between my DSLR and the app is unstable (the screen of my DSLR keep switching from connected to disconnected). Because of this, the app sometimes fails to take a photo.

Here is my config for this backend (used only for still), not an expert in gphoto2, so maybe there is a mistake in my config.

```
      {
        "enabled": true,
        "description": "NIKOND5300",
        "backend_config": {
          "orientation": "1: 0°",
          "camera_standby_when_inactive": true,
          "camera_standby_when_inactive_time": 10,
          "backend_type": "Gphoto2",
          "parameterset_device_init": [
            {
              "enabled": true,
              "name": "capturetarget",
              "value": "Mémoire interne",
              "note": ""
            },
            {
              "enabled": false,
              "name": "shutterspeed",
              "value": "1/50",
              "note": ""
            },
            {
              "enabled": false,
              "name": "iso",
              "value": "",
              "note": ""
            },
            {
              "enabled": true,
              "name": "viewfinder",
              "value": "0",
              "note": ""
            }
          ],
          "parameterset_standby": [
            {
              "enabled": true,
              "name": "viewfinder",
              "value": "0",
              "note": ""
            }
          ],
          "parameterset_video": [
            {
              "enabled": true,
              "name": "viewfinder",
              "value": "1",
              "note": ""
            }
          ],
          "parameterset_still": [
            {
              "enabled": true,
              "name": "viewfinder",
              "value": "0",
              "note": "allows camera to autofocus fast in native mode not contrast mode"
            },
            {
              "enabled": true,
              "name": "capturetarget",
              "value": "Mémoire interne",
              "note": ""
            }
          ]
        }
```

**System (please complete the following information):**
 - OS: [e.g. Raspberry Pi 5 trixie 64bit]
 - Browser : chromium

**Comment by Briffou** [comment]
I think I've found it.

Apparently It was a parameter change on my Nikon directly 😞  (was on "auto" mode instead of P/A/S/M). Sorry for the noise !

**Comment by Briffou** [comment]
humm, no definitely a change of behaviour in v9, now when DSLR is in "P" mode, photobooth keep the connection alive with the DSLR, but then the autofocus is always on after the first shoot (was not the case in v8).

Edit: in fact, even in "P" mode, I still get 

```
ERROR
	26.août.26 15:14:23	service Gphoto2Backend interrupted at /home/thomas/.local/share/pipx/venvs/photobooth-app/lib/python3.13/site-packages/photobooth/services/backends/gphoto2.py:330, error: Error communicating with the camera: [-1] Erreur indéfinie	photobooth.utils.resilientservice	report	39
CRITICAL
	26.août.26 15:14:23	aborting capturing frame, camera disconnected? retry to connect [-1] Erreur indéfinie
```

in the log

Edit 2: Ok, maybe this errors are in fact related to "capturetarget" option. 

Still have the app keeping the autofocus on after a shoot.

**Comment by Briffou** [comment]
Some DEBUG logs:

```
2026-08-26 18:42:30,265 [    INFO] started container (container.py:59)
2026-08-26 18:42:30,303 [   DEBUG] lifecycle hook installing signal to handle app shutdown (application.py:50)
2026-08-26 18:42:30,512 [   DEBUG] Gphoto2Backend-resilient service start running service logic (resilientservice.py:101)
2026-08-26 18:42:30,512 [    INFO] camera not yet configured after startup, apply device init config now on backend Gphoto2Backend (abstractbackend.py:231)
2026-08-26 18:42:30,513 [   DEBUG] configure camera during device init (gphoto2.py:84)
2026-08-26 18:42:30,659 [    INFO] sync files to 'NAS:/photo/PhotoBooth' (regular_synchronizer.py:87)
2026-08-26 18:42:30,808 [   DEBUG] Camera setting 'capturetarget' changed from 'Mémoire interne' to 'Mémoire interne' (Mémoire interne) (gphoto2.py:146)
2026-08-26 18:42:30,808 [   DEBUG] Camera setting 'viewfinder' changed from '0' to '0' (0) (gphoto2.py:146)
2026-08-26 18:42:30,810 [    INFO] changing mode from None to standby on backend Gphoto2Backend (abstractbackend.py:234)
2026-08-26 18:42:30,810 [   DEBUG] configure camera optimized for standby (gphoto2.py:96)
2026-08-26 18:42:30,822 [    INFO] changing mode completed (abstractbackend.py:247)
2026-08-26 18:42:31,951 [    INFO] All enabled rclone jobs finished, waiting for next run... (regular_synchronizer.py:100)
2026-08-26 18:42:32,321 [   DEBUG] camera livestream timeout (1/3) (acquisition.py:38)
2026-08-26 18:42:34,321 [   DEBUG] camera livestream timeout (2/3) (acquisition.py:38)
2026-08-26 18:42:36,231 [   DEBUG] WebcamV4lBackend:0-resilient service start running service logic (resilientservice.py:101)
2026-08-26 18:42:36,231 [    INFO] webcam device index: 0 (webcamv4l.py:160)
2026-08-26 18:42:36,232 [    INFO] webcam name: HD Pro Webcam C920: HD Pro Webc (webcamv4l.py:161)
2026-08-26 18:42:36,232 [    INFO] camera not yet configured after startup, apply device init config now on backend WebcamV4lBackend:0 (abstractbackend.py:231)
2026-08-26 18:42:36,232 [    INFO] changing mode from None to video on backend WebcamV4lBackend:0 (abstractbackend.py:234)
2026-08-26 18:42:36,243 [    INFO] requested resolution is 1280x720, format MJPEG (webcamv4l.py:66)
2026-08-26 18:42:36,244 [    INFO]    actual resolution is 1280x720, format MJPEG (webcamv4l.py:67)
2026-08-26 18:42:36,244 [    INFO] changing mode completed (abstractbackend.py:247)
2026-08-26 18:42:36,313 [   DEBUG] SSE clients connected: [Address(host='127.0.0.1', port=36032)] (sse_.py:204)
2026-08-26 18:42:36,336 [   DEBUG] camera livestream timeout (3/3) (acquisition.py:38)
2026-08-26 18:42:36,337 [   ERROR] failed to get frame after max retries, closing stream (acquisition.py:49)
2026-08-26 18:42:36,338 [   DEBUG] SSE clients connected: [Address(host='127.0.0.1', port=36032), Address(host='192.168.1.21', port=36366)] (sse_.py:204)
2026-08-26 18:42:36,369 [   DEBUG] SSE clients connected: [Address(host='127.0.0.1', port=36032), Address(host='192.168.1.21', port=36366), Address(host='192.168.1.21', port=36374)] (sse_.py:204)
2026-08-26 18:42:59,094 [    INFO] trigger action_type='image', action_index=0, starting job model: jobmodel=<JobModelImage> job-id=63106580-5be6-45c2-87aa-e0d88964de79 total captures to take=1 (processing.py:206)
2026-08-26 18:43:05,901 [    INFO] current capture (1/1, remaining 0) (image.py:47)
2026-08-26 18:43:06,045 [    INFO] taking hq picture (gphoto2.py:199)
2026-08-26 18:43:06,046 [    INFO] changing mode from standby to still on backend Gphoto2Backend (abstractbackend.py:234)
2026-08-26 18:43:06,046 [   DEBUG] configure camera optimized for still capture (gphoto2.py:92)
2026-08-26 18:43:06,554 [    INFO] changing mode completed (abstractbackend.py:247)
2026-08-26 18:43:08,363 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d10b changed, "recordingmedia" to "Carte"' (gphoto2.py:238)
2026-08-26 18:43:08,367 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1b2 changed, "Info Display Error Status" to "0"' (gphoto2.py:238)
2026-08-26 18:43:08,387 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1a4 changed, "liveviewprohibit" to "Live View prohibit conditions: Pending unretrieved SDRAM image,Processing of shooting operation"' (gphoto2.py:238)
2026-08-26 18:43:08,392 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1b4 changed, "continousshootingcount" to "8,000000"' (gphoto2.py:238)
2026-08-26 18:43:08,551 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1b4 changed, "continousshootingcount" to "8,000000"' (gphoto2.py:238)
2026-08-26 18:43:09,026 [   DEBUG] Event 'GP_EVENT_FILE_ADDED' received', event data is '<Swig Object of type 'CameraFilePath *' at 0x7ffebc12b130>' (gphoto2.py:235)
2026-08-26 18:43:09,034 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1a4 changed, "liveviewprohibit" to "Live View prohibit conditions: Pending unretrieved SDRAM image,Processing of shooting operation"' (gphoto2.py:238)
2026-08-26 18:43:09,090 [   DEBUG] Event 'GP_EVENT_UNKNOWN' received', event data is 'PTP Property 0000d1b4 changed, "continousshootingcount" to "9,000000"' (gphoto2.py:238)
2026-08-26 18:43:09,092 [   DEBUG] Event 'GP_EVENT_CAPTURE_COMPLETE' received, capture is complete, continue to download capture. (gphoto2.py:232)
2026-08-26 18:43:09,092 [    INFO] got captured_files=[('/', 'capt0000.jpg')] (gphoto2.py:240)
2026-08-26 18:43:09,092 [    INFO] determined file_to_download=('/', 'capt0000.jpg') (gphoto2.py:249)
2026-08-26 18:43:09,533 [   DEBUG] client disconnected while sending a frame (acquisition.py:99)
2026-08-26 18:43:09,533 [   DEBUG] client disconnected while sending a frame (acquisition.py:99)
2026-08-26 18:43:10,165 [    INFO] capture media/processed_full/20260826-184309-439019.jpg processed (image.py:76)
2026-08-26 18:43:10,166 [    INFO] add 1 results to db (processing.py:51)
2026-08-26 18:43:10,975 [   DEBUG] immediate sync finished: CopyOperation: NAS:/photo/PhotoBooth/media/camera_original/20260826-184309-439019.jpg @prio 12 (immediate_synchronizer.py:149)
2026-08-26 18:43:11,486 [   DEBUG] immediate sync finished: CopyOperation: NAS:/photo/PhotoBooth/media/processed_full/20260826-184309-439019.jpg @prio  9 (immediate_synchronizer.py:149)
2026-08-26 18:43:17,776 [    INFO] request delete files of <Mediaitem> (20260826-184309-439019.jpg) (files.py:22)
2026-08-26 18:43:17,776 [    INFO] moving <Mediaitem> (20260826-184309-439019.jpg) to recycle directory (files.py:26)
2026-08-26 18:43:17,779 [    INFO] deleted files of <Mediaitem> (20260826-184309-439019.jpg) (files.py:34)
2026-08-26 18:43:17,811 [   DEBUG] immediate sync finished: DeleteOperation: NAS:/photo/PhotoBooth/media/processed_full/20260826-184309-439019.jpg @prio 19 (immediate_synchronizer.py:149)
2026-08-26 18:43:20,469 [   DEBUG] client disconnected while sending a frame (acquisition.py:99)
2026-08-26 18:43:25,633 [   DEBUG] client disconnected while sending a frame (acquisition.py:99)
2026-08-26 18:43:35,627 [    INFO] getting latest logfile: log/photobooth_20260826.log (debug.py:21)
```

**Comment by Briffou** [comment]
To summarize, two things happen since I updated :

- the connection between the app and the DSLR is sometimes unstable (without my being able to identify any specific reasons). In this case I have `ERROR	26.août.26 11:54:21	service Gphoto2Backend interrupted at /home/thomas/.local/share/pipx/venvs/photobooth-app/lib/python3.13/site-packages/photobooth/services/backends/gphoto2.py:330, error: Error communicating with the camera: [-1] Erreur indéfinie	photobooth.utils.resilientservice	report	39`
- when the connection is stable, the autofocus gets stuck after the first shoot. Maybe related to https://github.com/photobooth-app/photobooth-app/discussions/772

**Comment by mgineer85** [comment]
Hi, there have been changes to the camera handling in v9 , which can introduce this buggy behavior. I am on a trip in china right now so I have no access to my hardware. I try to check it as soon as possible after my return next week.

**Comment by mgineer85** [comment]
Hi, could you test if adding `self._mode_machine.request_video()` or `self._mode_machine.request_standby()` as shown below solves it?
It would reset the camera to video mode / standby right after the still - which is what we probably want if there is a dedicated livestream backend...

It is in the file https://github.com/photobooth-app/photobooth-app/blob/fdb939ed846bff9ef2decd00944f040e869b7533/src/photobooth/services/backends/abstractbackend.py#L356

```python

    def wait_for_still_file(self, index_subdevice: int = 0) -> Path:
        req = StillRequest(uuid.uuid4(), subdevice_index=index_subdevice)

        self._mode_machine.request_still()

        with self._hires_lock:
            self._hires_queue.append(req)

        with req.condition:
            ok = req.condition.wait(timeout=8)

            # TODO: add logic to return to standby or video if this backend is NOT the livestream-backend.
            # reason: if it is the livestream backend, the frontend would ask for a stream and the camera switch to video
            # for DSLR usually the viewfinder is reset when reverting to video again and the camera is ready for the next capture.
            self._mode_machine.request_video()

            if not ok:
                raise TimeoutError("timeout waiting for hires frame")

            filepath = req.result_file
            assert filepath

            set_exif_orientation(filepath, self._orientation)

            return filepath

```

**Comment by Briffou** [comment]
It seems that adding

```
self._mode_machine.request_standby()
```

indeed force the camera to go in standby mode after the still (confirmed by the logs). 

But I also need to add `autofocusdrive=0` to the camera's standby settings to disable autofocus; otherwise, it remained active.

**Comment by mgineer85** [comment]
That’s correct but without mode switch forced there is no way to send that command, that’s why I suggested adding it. Should have mentioned the additional setting required though but glad you figured it out

**Comment by k7m2000** [comment]
I'm also having problems with the camera connection and the livestream. Sometimes the livestream and photo capture work, sometimes only the photos, and sometimes nothing at all.
Do you have any updates on this yet?

**Comment by mgineer85** [comment]
Did you try to add the code and set the events as described above already?

**Comment by Briffou** [comment]
Just to confirm that there are no issues on my side with v9.0.0 since I added the code allowing the camera to go in standby mode after a still (with `autofocusdrive=0` in the camera's standby parameter)
